//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 12:20:41 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/po.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package artcitlocator.streaming.configuration.jaxb.entity;
