//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 12:20:41 AM CET 
//


package artcitlocator.streaming.configuration.jaxb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TwitterAccount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwitterAccount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OAuthConsumerKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OAuthConsumerSecret" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OAuthAccessToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OAuthAccessTokenSecret" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwitterAccount", propOrder = {
    "oAuthConsumerKey",
    "oAuthConsumerSecret",
    "oAuthAccessToken",
    "oAuthAccessTokenSecret"
})
public class TwitterAccount {

    @XmlElement(name = "OAuthConsumerKey", required = true)
    protected String oAuthConsumerKey;
    @XmlElement(name = "OAuthConsumerSecret", required = true)
    protected String oAuthConsumerSecret;
    @XmlElement(name = "OAuthAccessToken", required = true)
    protected String oAuthAccessToken;
    @XmlElement(name = "OAuthAccessTokenSecret", required = true)
    protected String oAuthAccessTokenSecret;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the oAuthConsumerKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOAuthConsumerKey() {
        return oAuthConsumerKey;
    }

    /**
     * Sets the value of the oAuthConsumerKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOAuthConsumerKey(String value) {
        this.oAuthConsumerKey = value;
    }

    /**
     * Gets the value of the oAuthConsumerSecret property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOAuthConsumerSecret() {
        return oAuthConsumerSecret;
    }

    /**
     * Sets the value of the oAuthConsumerSecret property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOAuthConsumerSecret(String value) {
        this.oAuthConsumerSecret = value;
    }

    /**
     * Gets the value of the oAuthAccessToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOAuthAccessToken() {
        return oAuthAccessToken;
    }

    /**
     * Sets the value of the oAuthAccessToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOAuthAccessToken(String value) {
        this.oAuthAccessToken = value;
    }

    /**
     * Gets the value of the oAuthAccessTokenSecret property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOAuthAccessTokenSecret() {
        return oAuthAccessTokenSecret;
    }

    /**
     * Sets the value of the oAuthAccessTokenSecret property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOAuthAccessTokenSecret(String value) {
        this.oAuthAccessTokenSecret = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
