//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 11:27:29 PM CET 
//


package artcitlocator.streaming.jaxb.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isRetweet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="favoriteCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="retweetCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="user" type="{http://tempuri.org/po.xsd}User"/>
 *         &lt;element name="geoPos" type="{http://tempuri.org/po.xsd}GeoPosition"/>
 *         &lt;element name="place" type="{http://tempuri.org/po.xsd}Place"/>
 *         &lt;sequence>
 *           &lt;element name="mediaEntities" type="{http://tempuri.org/po.xsd}MediaEntity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="hashtags" type="{http://tempuri.org/po.xsd}Hashtag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="symbols" type="{http://tempuri.org/po.xsd}Symbol" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="urlEntities" type="{http://tempuri.org/po.xsd}URL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "text",
    "isRetweet",
    "createTime",
    "favoriteCount",
    "retweetCount",
    "source",
    "id",
    "language",
    "user",
    "geoPos",
    "place",
    "mediaEntities",
    "hashtags",
    "symbols",
    "urlEntities"
})
@XmlRootElement(name = "tweet")
public class Tweet {

    @XmlElement(required = true)
    protected String text;
    protected boolean isRetweet;
    protected long createTime;
    protected int favoriteCount;
    protected int retweetCount;
    @XmlElement(required = true)
    protected String source;
    protected long id;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected User user;
    @XmlElement(required = true)
    protected GeoPosition geoPos;
    @XmlElement(required = true)
    protected Place place;
    protected List<MediaEntity> mediaEntities;
    protected List<Hashtag> hashtags;
    protected List<Symbol> symbols;
    protected List<URL> urlEntities;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the isRetweet property.
     * 
     */
    public boolean isIsRetweet() {
        return isRetweet;
    }

    /**
     * Sets the value of the isRetweet property.
     * 
     */
    public void setIsRetweet(boolean value) {
        this.isRetweet = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     */
    public long getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     */
    public void setCreateTime(long value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the favoriteCount property.
     * 
     */
    public int getFavoriteCount() {
        return favoriteCount;
    }

    /**
     * Sets the value of the favoriteCount property.
     * 
     */
    public void setFavoriteCount(int value) {
        this.favoriteCount = value;
    }

    /**
     * Gets the value of the retweetCount property.
     * 
     */
    public int getRetweetCount() {
        return retweetCount;
    }

    /**
     * Sets the value of the retweetCount property.
     * 
     */
    public void setRetweetCount(int value) {
        this.retweetCount = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the geoPos property.
     * 
     * @return
     *     possible object is
     *     {@link GeoPosition }
     *     
     */
    public GeoPosition getGeoPos() {
        return geoPos;
    }

    /**
     * Sets the value of the geoPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoPosition }
     *     
     */
    public void setGeoPos(GeoPosition value) {
        this.geoPos = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the mediaEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mediaEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMediaEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MediaEntity }
     * 
     * 
     */
    public List<MediaEntity> getMediaEntities() {
        if (mediaEntities == null) {
            mediaEntities = new ArrayList<MediaEntity>();
        }
        return this.mediaEntities;
    }

    /**
     * Gets the value of the hashtags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hashtags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHashtags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hashtag }
     * 
     * 
     */
    public List<Hashtag> getHashtags() {
        if (hashtags == null) {
            hashtags = new ArrayList<Hashtag>();
        }
        return this.hashtags;
    }

    /**
     * Gets the value of the symbols property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the symbols property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSymbols().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Symbol }
     * 
     * 
     */
    public List<Symbol> getSymbols() {
        if (symbols == null) {
            symbols = new ArrayList<Symbol>();
        }
        return this.symbols;
    }

    /**
     * Gets the value of the urlEntities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlEntities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrlEntities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link URL }
     * 
     * 
     */
    public List<URL> getUrlEntities() {
        if (urlEntities == null) {
            urlEntities = new ArrayList<URL>();
        }
        return this.urlEntities;
    }

}
