//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 11:26:58 PM CET 
//


package artcitlocator.streaming.twitter.options.jaxb.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Locations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Locations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XCoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="YCoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Locations", propOrder = {
    "xCoord",
    "yCoord",
    "name"
})
public class Locations {

    @XmlElement(name = "XCoord")
    protected double xCoord;
    @XmlElement(name = "YCoord")
    protected double yCoord;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the xCoord property.
     * 
     */
    public double getXCoord() {
        return xCoord;
    }

    /**
     * Sets the value of the xCoord property.
     * 
     */
    public void setXCoord(double value) {
        this.xCoord = value;
    }

    /**
     * Gets the value of the yCoord property.
     * 
     */
    public double getYCoord() {
        return yCoord;
    }

    /**
     * Sets the value of the yCoord property.
     * 
     */
    public void setYCoord(double value) {
        this.yCoord = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

}
